// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPaE_pvq00zX2TwgWMy2NKQbGpVoe1k5U',
    appId: '1:733443501009:web:5077c4121851e8b997cef0',
    messagingSenderId: '733443501009',
    projectId: 'petpulse-app',
    authDomain: 'petpulse-app.firebaseapp.com',
    storageBucket: 'petpulse-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvs_EbMTzbIOldeC8sgJ_gmFF__QBDb4',
    appId: '1:733443501009:android:14c792df8b99b2d297cef0',
    messagingSenderId: '733443501009',
    projectId: 'petpulse-app',
    storageBucket: 'petpulse-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyFS7TZfXo3ZwTC3kKLSOlMKC-MVAaGM',
    appId: '1:733443501009:ios:be1dca9bac7570d397cef0',
    messagingSenderId: '733443501009',
    projectId: 'petpulse-app',
    storageBucket: 'petpulse-app.appspot.com',
    androidClientId: '733443501009-o6tcoq9qgkehoeh5di1gqoel2qt48b7o.apps.googleusercontent.com',
    iosClientId: '733443501009-h8v430ln3d8ovdes444042bsdrcv5ku3.apps.googleusercontent.com',
    iosBundleId: 'com.example.petpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyFS7TZfXo3ZwTC3kKLSOlMKC-MVAaGM',
    appId: '1:733443501009:ios:d0a7e46d0313f59697cef0',
    messagingSenderId: '733443501009',
    projectId: 'petpulse-app',
    storageBucket: 'petpulse-app.appspot.com',
    androidClientId: '733443501009-o6tcoq9qgkehoeh5di1gqoel2qt48b7o.apps.googleusercontent.com',
    iosClientId: '733443501009-kuc1qedqouampfmg6v493ricjilrg6k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.petpulse.RunnerTests',
  );
}
